# -*- coding: utf-8 -*-
"""Rock,paper,scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ6oYZOhFEvzq5LbyuCQlIZeQwQtKXRz
"""

import random

# --------------------------
# Rock-Paper-Scissors Game
# --------------------------

choices = ["rock", "paper", "scissors"]

print("🎮 Welcome to Rock-Paper-Scissors!")
print("Type 'quit' anytime to stop.\n")

while True:
    user = input("Enter rock, paper, or scissors: ").lower()

    if user == "quit":
        print("👋 Thanks for playing! Goodbye!")
        break

    if user not in choices:
        print("⚠️ Invalid choice. Please try again.\n")
        continue

    computer = random.choice(choices)
    print(f"🧠 Computer chose: {computer}")

    # Decide winner
    if user == computer:
        print("😐 It's a tie!\n")
    elif (
        (user == "rock" and computer == "scissors") or
        (user == "paper" and computer == "rock") or
        (user == "scissors" and computer == "paper")
    ):
        print("🎉 You win!\n")
    else:
        print("💻 Computer wins!\n")